version: 2.0.0.{build}
image: Visual Studio 2019
configuration: Release
skip_commits:
  files:
  - Docs/*
  - '**/*.md'
  - 'mkdocs.yml'
  - '.readthedocs.yml'
  - '**/*.bat'
  - '.gitignore'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: TextSerializer.sln
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: FCTeK6seq0e90uq+7DLRVKbseyxT3/BDaTNCEWTQ2MRjvS3x533Blqs1dpvfRVt3
  on:
    branch: master